name: Dependency graph Docker in Actions

on: push

jobs:
  build:
   name: Build
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2

    - name: Run Commands inside Docker Container. Get dg alert if enabled
      run: |
        # fetch the dependency graph SPDX SBOM JSON file
        curl -L -o $RUNNER_TEMP/sbom.json $GITHUB_WORKSPACE\
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github.repository }}/dependency-graph/sbom

        # parsing the fetched SBOM JSON file and transforming it into SPDX SBOM format so trivy can process
        cat $RUNNER_TEMP/sbom.json | jq '.sbom' > $RUNNER_TEMP/sbom.json
        sed -i -e '${/^$/d;}' $RUNNER_TEMP/sbom.json

        # modify the SPDX JSON into DD generic finding format
        jq -c ' {findings: [ .packages[] |{
          title: "\(.name) \(.versionInfo)",
          active: true,
          verified: true,
          description: "N/A",
          severity: "Info",
          mitigation: "N/A",
          date: "2024-04-22",
          cve: 0,
          cwe: 0,
          cvssv3: "N/A",
          file_path: null,
          line: 11,
          "vuln_id_from_tool": .SPDXID,
        }]}' $RUNNER_TEMP/sbom.json > $RUNNER_TEMP/sbom_generic.json

        # Check SBOM file 
        ls -lah $GITHUB_WORKSPACE
        cat $RUNNER_TEMP/sbom_generic.json
        #upload-results-s3.sh $RUNNER_TEMP/sbom_generic.json
