name: Dependabot Docker in Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: zerosource/dojo-s3import-github-dependabot-and-dependency-graph
      env:
        LAMBDA_URL: ${{ secrets.LAMBDA_URL }}
        APP_ID: ${{ secrets.APP_ID_SEMGREP }}
        
    steps:
    - uses: actions/checkout@v2

    - name: Generate IAT from Github App for the current repository
      uses: actions/create-github-app-token@c4fa18d55c5d49e6a2793e351ea4938322c61072 #v1
      id: app-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Run Commands inside Docker Container. Get dependabot alert if enabled
      run: |
        curl --request GET -L -o $RUNNER_TEMP/dependabot-results.json \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github.repository }}/dependabot/alerts
        
        ls -lah $GITHUB_WORKSPACE
        #upload-results-s3.sh $RUNNER_TEMP/dependabot-results.json

