name: Zap Proxy Docker Container in Actions

on:
  workflow_dispatch:

jobs:
  run_semgrep:
    runs-on: ubuntu-latest
    container: 
      image: zerosource/dojo-s3import-zap
      env:
        LAMBDA_URL: ${{ secrets.LAMBDA_URL }}
        APP_ID: ${{ secrets.APP_ID_ZAP }}
        
    steps:
    - uses: actions/checkout@v2

    - name: Run Commands inside Docker Container
      run: |
        # Scanning an app running on the host OS
        status_code=$(curl -LI http://$(ipconfig getifaddr en0):3000 -o /dev/null -w '%{http_code}\n' -s)
        if [ $status_code -eq 200 ]; then
            echo "The application is running."
            docker run -v $(pwd):/zap/wrk/:rw -t softwaresecurityproject/zap-stable:latest zap-full-scan.py \
            -t http://$(ipconfig getifaddr en0):65412 -d -D 4 -g gen.conf -x $RUNNER_TEMP/zap_output.xml
        else 
            echo "The application is not reachable. Please check the application."
        fi

        # scan external app (internet accessible)
        

        for text in "${{ vars.URLs }}"; do
            if [[ "$text" != *.com* ]]; then
              echo "Please add list of scanning URLs in GitHub Action variables."
            else
              echo "${{ vars.URLs }}" | while IFS= read -r line; do
              docker run -v $(pwd):/zap/wrk/:rw -t softwaresecurityproject/zap-stable:latest zap-full-scan.py \
              -t $line -d -D 4 -g gen.conf -x $RUNNER_TEMP/zap_output.xml
              done
            fi
          done 

        mv $RUNNER_TEMP/zap_output.xml $RUNNER_TEMP/zap_output.zapx


        upload-results-s3.sh $RUNNER_TEMP/zap_output.zapx